apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-master-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projet-master
  template:
    metadata:
      labels:
        app: projet-master
    spec:
      containers:
      - name: projet-master-container
        image: 816069150405.dkr.ecr.us-east-1.amazonaws.com/projet-master:v1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          - name: CLERK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: CLERK_SECRET_KEY
          - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
          - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
          - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
          - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
          - name: REPLICATE_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REPLICATE_API_TOKEN
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DATABASE_URL
          - name: STRIPE_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: STRIPE_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: projet-master-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: projet-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000