apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: cGtfdGVzdF9hRzl3WldaMWJDMXphSEpwYlhBdE5EVXVZMnhsY21zdVlXTmpiM1Z1ZEhNdVpHVjJKQQ==
  CLERK_SECRET_KEY: c2tfdGVzdF9Ma0lWemdSYVh5Zk1HSFhoQ1A5NTB1R0VoU2t0dUI2T0FHMWJ
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: L3NpZ24taW4=
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: L3NpZ24tdXA=
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: L2Rhc2hib2FyZA==
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: L2Rhc2hib2FyZA==
  REPLICATE_API_TOKEN: cjhfNlVyMTFDQmJ2aVFjNkIxaVAyZUFwVmNmMWRZRWNDajFNWjVJZQ==
  DATABASE_URL: bXlzcWw6Ly9hdm5hZG1pbjpBVk5TX0JZeXo2MWMtUmFWczR3Zy1ZT0VAbXlzcWwtMTY4OGQ5YjYtYXJtZWxtYW5vbWJvc29hLmkuYWl2ZW5jbG91ZC5jb206MTY1NTkvZGVmYXVsdGRiP3NzbC1tb2RlPVJFUVVJUkVE
  STRIPE_API_KEY: c2tfdGVzdF81MVB5dDNPQ1hXNWpacEc2aVhZZk4zb2VScU5lelZkbXV6dkV1WURmTzJQNXRScXB5Snd4ZndnYWluWXVlYUw5N0JhNXZ3Vm5PelN1bVRpUE02NGRrYnBpdzAwM1ZIVUFBDQE=