name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create ECR repository if not exists
      run: |
        aws ecr describe-repositories --repository-names projet-master || \
        aws ecr create-repository --repository-name projet-master --region us-east-1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: projet-master
        IMAGE_TAG: v1.0.0
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name projet-master-eks --region us-east-1

    - name: Create namespace if not exists
      run: |
        kubectl get namespace productions || kubectl create namespace productions
        kubectl config set-context --current --namespace=productions

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deploy.yaml

    - name: Force restart pods
      run: kubectl rollout restart deployment/projet-master-deployment